name: spotnmf
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  # Core packages
  - anndata=0.11.3
  - numpy=1.26.4
  - pandas=2.2.3
  - scanpy=1.10.4
  - matplotlib-base=3.10.0
  - scikit-learn=1.6.1
  - scipy=1.12.0
  - seaborn=0.13.2
  - igraph=0.10.15
  - python-igraph=0.11.8
  - leidenalg=0.10.2
  - h5py=3.12.1
  - umap-learn=0.5.7
  - pygam=0.9.1
  - networkx=3.4.2
  - numba=0.60.0
  - llvmlite=0.43.0
  - fastcluster=1.2.6
  - statsmodels=0.14.4
  - patsy=1.0.1
  - session-info=1.0.0
  - natsort=8.4.0
  - tqdm=4.67.1
  - colorama=0.4.6
  - fonttools=4.55.6
  - pillow=11.1.0
  - joblib=1.4.2
  - future=1.0.0
  - packaging=24.2
  - pyparsing=3.2.1
  - six=1.17.0
  - typing
  - typing_extensions=4.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - python-dateutil=2.9.0.post0
  - pytz=2024.1
  - stdlib-list=0.11.0
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - exceptiongroup=1.2.2
  - legacy-api-wrap=1.4.1
  - cycler=0.12.1
  - contourpy=1.3.1
  - kiwisolver=1.4.8
  - markupsafe=2.1.5
  - jinja2=3.1.4
  - os
  - adjust_text
  # CUDA/torch dependencies typically installed via pip (see below)
  - pip
  - pip:
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - torchaudio==2.6.0+cu118
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - triton==3.2.0
      # Bio/specialized
      - rbo==0.1.3
      - distinctipy==1.3.4
      - gprofiler-official==1.0.0
      - requests==2.32.3
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - idna==3.10
      - filelock==3.13.1
      - fsspec==2024.6.1
      - sympy==1.13.1
      - munkres==1.1.4
      - python-utils==3.9.1
      - progressbar2==4.5.0
      - unicodedata2==16.0.0
      - wheel==0.45.1
      - urllib3==2.3.0

# Remove "prefix" line if you want to share/distribute!
